/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TestNative_DiskInfo */

#ifndef _Included_TestNative_DiskInfo
#define _Included_TestNative_DiskInfo
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
