/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TestNative */

#ifndef _Included_TestNative
#define _Included_TestNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestNative
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_TestNative_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     TestNative
 * Method:    getName
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_TestNative_getName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     TestNative
 * Method:    setArray
 * Signature: ([Z)V
 */
JNIEXPORT void JNICALL Java_TestNative_setArray
  (JNIEnv *, jobject, jbooleanArray);

/*
 * Class:     TestNative
 * Method:    getStringArray
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_TestNative_getStringArray
  (JNIEnv *, jobject);

/*
 * Class:     TestNative
 * Method:    getStruct
 * Signature: ()LDiskInfo;
 */
JNIEXPORT jobject JNICALL Java_TestNative_getStruct
  (JNIEnv *, jobject);

/*
 * Class:     TestNative
 * Method:    getStructArray
 * Signature: ()[LDiskInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_TestNative_getStructArray
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
